# https://developers.home-assistant.io/docs/apps/configuration#app-configuration
name: Pagekite
version: "1.0.1"
slug: pagekite
description: Expose Home Assistant via a Pagekite reverse tunnel
url: https://codeberg.org/DoubleMalt/homeassistant-pagekite/src/branch/main/pagekite
arch:
  - aarch64
  - amd64
init: false
host_network: true
startup: services
boot: auto
stage: stable
panel_icon: mdi:tunnel
options:
  frontend: your-pagekite-server.example.com:443
  kitename: ha.your-domain.tld
  secret: CHANGE_ME
  ha_port: 8123
  le_port: 80
  enable_http: true
  enable_https: true
schema:
  frontend: str
  kitename: str
  secret: password
  ha_port: port
  le_port: port
  enable_http: bool
  enable_https: bool
